name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:   # <-- lets you trigger it from the Actions tab manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar   # <-- adjust if your JAR lands somewhere else

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
