name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    environment: releases
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # --- Create settings.xml dynamically for GitHub Packages ---
      - name: Create Maven settings.xml
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>choice21hax</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload built JAR (for download from Actions tab)
        uses: actions/upload-artifact@v4
        with:
          name: litecmdlogger
          path: target/*.jar

      - name: Publish to GitHub Packages
        run: mvn -B deploy -s $HOME/.m2/settings.xml
